version: '3'
services:
  postgres:
    image: postgres:10.3
    container_name: postgres-nestjs
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  wait-postgres:
    image: waisbrot/wait
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - TARGETS=postgres:5432
